{
 "title": "Adjusted close price vs predicted price",
 "time": { "from": "2024-10-01T03:00:00.000Z", "to": "now" },
 "panels": [
  {
   "title": "AMZN Adjusted close price vs prediction price",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select s.date, s.adj_close, p.prediction from stock_ohlc s inner join stock_prediction p ON s.date = p.date AND s.symbol = p.symbol where s.symbol = 'amzn' order by s.date asc;"
    }
   ]
  },
  {
   "title": "AMZN next close price predicton",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT date, prediction FROM stock_prediction WHERE symbol = 'amzn' ORDER BY date DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "GOOG Adjusted close price vs predicted price",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "select s.date, s.adj_close, p.prediction from stock_ohlc s inner join stock_prediction p ON s.date = p.date AND s.symbol = p.symbol where s.symbol = 'goog' order by s.date asc;"
    }
   ]
  },
  {
   "title": "GOOG next close price prediction",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT date, prediction FROM stock_prediction WHERE symbol = 'goog' ORDER BY date DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "MSFT Adjusted close price vs predicted price",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "select s.date, s.adj_close, p.prediction from stock_ohlc s inner join stock_prediction p ON s.date = p.date AND s.symbol = p.symbol where s.symbol = 'msft' order by s.date asc;"
    }
   ]
  },
  {
   "title": "MSFT next close price prediction",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT date, prediction FROM stock_prediction WHERE symbol = 'msft' ORDER BY date DESC LIMIT 1 "
    }
   ]
  }
 ]
}