{
 "title": "Evidently Dashboard",
 "description": "Some evidently metrics",
 "time": { "from": "2024-07-01T03:00:00.000Z", "to": "now" },
 "panels": [
  {
   "title": "AMNZ Prediction Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT date AS \"time\", prediction_drift AS \"value\" FROM evidently_metrics WHERE symbol = 'amzn' LIMIT 50 "
    }
   ]
  },
  {
   "title": "AMZN Number of Drifted Columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT date AS \"time\", num_drifted_columns AS \"value\" FROM evidently_metrics WHERE symbol = 'amzn' LIMIT 50 "
    }
   ]
  },
  {
   "title": "GOOG Prediction Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT date AS \"time\", prediction_drift AS \"value\" FROM evidently_metrics WHERE symbol = 'goog' LIMIT 50 "
    }
   ]
  },
  {
   "title": "GOOG Number of Drifted Columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT date AS \"time\", num_drifted_columns AS \"value\" FROM evidently_metrics WHERE symbol = 'goog' LIMIT 50 "
    }
   ]
  },
  {
   "title": "MSFT Prediction Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT date AS \"time\", prediction_drift AS \"value\" FROM evidently_metrics WHERE symbol = 'msft' LIMIT 50 "
    }
   ]
  },
  {
   "title": "MSFT Number of Drifted Columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT date AS \"time\", num_drifted_columns AS \"value\" FROM evidently_metrics WHERE symbol = 'msft' LIMIT 50 "
    }
   ]
  }
 ]
}