name: Push-to-EC2 and Upload to S3

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Main Branch
        uses: actions/checkout@main

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: "us-east-1"

      - name: Set environment variables
        run: |
          echo "HOST=${{ secrets.HOST_DNS }}" >> $GITHUB_ENV
          echo "USERNAME=${{ secrets.USERNAME }}" >> $GITHUB_ENV
          echo "PORT=22" >> $GITHUB_ENV
          echo "SSHKEY=${{ secrets.EC2_SSH_KEY }}" >> $GITHUB_ENV
          echo "TARGET=${{ secrets.TARGET_DIR }}" >> $GITHUB_ENV
    
      - name: Copy 'dags' folder
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          port: ${{ env.PORT }}
          key: ${{ env.SSHKEY }}
          source: "./dags"
          target: ${{ env.TARGET }}

      - name: Copy 'docker-airflow' folder
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          port: ${{ env.PORT }}
          key: ${{ env.SSHKEY }}
          source: "./docker-airflow"
          target: ${{ env.TARGET }}

      - name: Copy 'integration-test' folder
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          port: ${{ env.PORT }}
          key: ${{ env.SSHKEY }}
          source: "./integration-test"
          target: ${{ env.TARGET }}

      - name: Copy 'docker-compose-airflow.yaml' folder
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          port: ${{ env.PORT }}
          key: ${{ env.SSHKEY }}
          source: "./docker-compose-airflow.yaml"
          target: ${{ env.TARGET }}
  
      - name: Copy 'Makefile' folder
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          port: ${{ env.PORT }}
          key: ${{ env.SSHKEY }}
          source: "./Makefile"
          target: ${{ env.TARGET }}
