name: Push-to-EC2 and Upload to S3

on:
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Main Branch
        uses: actions/checkout@main

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: "us-east-1"
     
      - name: Deploy Code to airflow EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ vars.HOST_DNS }}
          username: ${{ vars.USERNAME }}
          port: 22
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./,!./docker-jupyter,!./docker-mlflow,!./docker-postgres,!./grafana,!./notebooks,!./terraform"
          target: ${{ vars.TARGET_DIR }}

