name: Push-to-EC2 and Upload to S3

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Main Branch
        uses: actions/checkout@main

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: "us-east-1"
     
      - name: Copy 'dags' folder
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          port: 22
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./dags"
          target: ${{ secrets.TARGET_DIR }}

      - name: Copy 'docker-airflow' folder
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          port: 22
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./docker-airflow"
          target: ${{ secrets.TARGET_DIR }}

      - name: Copy 'integration-test' folder
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          port: 22
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./integration-test"
          target: ${{ secrets.TARGET_DIR }}

      - name: Copy 'test' folder
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          port: 22
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./test"
          target: ${{ secrets.TARGET_DIR }}

      - name: Copy 'docker-compose-airflow.yaml' folder
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          port: 22
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./docker-compose-airflow.yaml"
          target: ${{ secrets.TARGET_DIR }}

      - name: Copy 'Makefile' folder
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          port: 22
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./Makefile"
          target: ${{ secrets.TARGET_DIR }}
  